### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by nickschurch** [drchriscole/ensemblUtils#1]
I'd like to suggest the following feature requests to _create_html_table.pl_ and _add_gene_name_column.pl_
1. an option to define the index of the column to use as the ensembl identifiers for annotation and html linking (rather than assuming the first column)
2. an option to definte the column index to insert the additional_gene name_ and _description_ columns, rather than hardcoing them into cols 1 & 2.
3. make create_html_table.pl operate with their gene ids or transcript ids.

Thanks

**Comment by drchriscole** [comment]
Sorted (1) and (2). See how you get on.
I may get around to (3).
